### ISSUE TITLE
Coordinate for signers 

### ISSUE THREAD

**Issue by GregMars** [CapSens/Universign#8]
Hello everybody, I'm using CapSens/Universign gem to create a transaction with universign. First of all, thank you 😄 . It's is really helpful.

I'm running through a problem with the position of the signature field.
 
here my code for this:

    document_from_content = Universign::Document.new(
        name:    'another.pdf',
        content: File.open("tmp/test.pdf").read
    )

    signer = Universign::TransactionSigner.new(
        first_name:   "Signer's first name",
        last_name:    "Signer's last name",
        email:        'test@gmail.com',
        phone_number: 'SOME_PHONE_NUMBER',
        success_url:  'https://my_app.com',
        signature:    Universign::SignatureField.new(coordinate: [37,684], page: 5)
    )

    transaction = Universign::Transaction.create(
        documents: [document_from_content],
        signers:   [signer],
        options:   { profile: 'default', final_doc_sent: false, handwritten_signature_mode: 0}
    )

I got a code 200 response from this. I can sign the pdf BUT signature stamps are not showing in the PDF generated by Universign when the transaction is completed.

Is it because of this configuration ? Or maybe I didn't understand well the different signatures configurations.

there is my question on stackoverflow :
https://stackoverflow.com/questions/64424793/ror-capsens-universign-signaturefield-the-coordinate-arent-working

I don't think this is really an issue. Can you help me with this ?

**Comment by Defoncesko** [comment]
Does this gem still maintained ?

**Comment by AntoineBecquet** [comment]
Hello,

sorry, I did have notifications enabled.

Your document, signer and signature field configurations seem good. I don't see any obvious error.

Do you reload the signed PDF from universign with `Universign::Transaction.new(transaction.transaction_id)` after it is signed ?

I never used the option `handwrittenSignatureMode`, are you sure of its usage ? The documentation says "0" disables the hand-written signature.

**Comment by GregMars** [comment]
Hello, 
thank for your reply. It's okay, i can define the signature_fields on the Universign::Document and this works fine. But with the
``Universign::TransactionSigner.new( signature:   Universign::SignatureField.new(coordinate: [37,684], page: 5) )`` there is a problem. I tried to change the ``attr_reader :signature``  on the TransactionSigner model to ``:signature_fields`` and this worked

**Comment by AntoineBecquet** [comment]
Hello,

Thank you for your feedback. 
There was indeed an error in the Readme, and the mix-up with `signature` field made it not obvious.
I fixed the Readme.
